name: 'run-vcpkg'
description: 'Run vcpkg to build dependencies.'
inputs:
  vcpkgDirectory:
    default: "./vcpkg",
    required: false,
    description: "The vcpkg's root directory. Specify the vcpkg's root directory. If not specified, it defaults to $(Build.BinariesDirectory)/vcpkg/ . When vcpkg is a Git submodule, specify the full path to it (e.g. '$(Build.SourcesDirectory)/vcpkg/') ."
  vcpkgGitURL:
      "label": "",
    default: "https://github.com/microsoft/vcpkg.git",
    required: false,
    description: "vcpkg URL Git repository. Specify the URL Git repository to download vcpkg from. Defaults to https://github.com/microsoft/vcpkg.git",
    
  vcpkgGitCommitId:
    description: "vcpkg Git tag/ref:",
    default: "",
    required: false,

  vcpkgTriplet:
    description: "The vcpkg triplet:",
    default: "",
    required: false,

  vcpkgArguments:
    description: "Arguments for 'vcpkg install':",
    default: "",
    required: true,
  
  vcpkgArtifactIgnoreEntries:
    description: "The entries to append to .artifactignore file, located in the vcpkg's root:",
    default: "!.git\n**/*\n!installed\n!/vcpkg\n!vcpkg.exe\n",
    required: false,

outputs:
  outVcpkgRootPath:
    description: 'The vcpkg location.'
  outvcpkgTriplet:
    description: 'The vcpkg triplet.'

runs:
  using: 'node12'
  main: 'src/vcpkg-action.js'